
# Para mas información sobre instrucciones del Dockerfile: https://docs.docker.com/engine/reference/builder/

# La instrucción FROM inicializa una nueva etapa de construcción y establece la imagen base 
# para instrucciones posteriores. Un Dockerfile válido debe comenzar con una instrucción FROM. 
# La imagen puede ser cualquier imagen válida; es especialmente fácil comenzar usando una imagen de los repositorios públicos.
FROM ubuntu:20.04

# Un ENTRYPOINT permite configurar a un contenedor para que este corra como un ejecutable
ENTRYPOINT echo "Hola mundo"
